-- INSERT INTO person(name, age, address) VALUES ( 'fan', 22, 'Shanghai')
-- INSERT INTO person(name, age, address) VALUES ( 'zhang', 21, 'Chengdu')
-- INSERT INTO person(name, age, address) VALUES ( 'li', 23, 'Beijing')
-- INSERT INTO person( name, age, address) VALUES ( 'Gao', 24, 'Nanjing')